version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: miapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/miapp
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    env_file:
    - ./backend/.env


#  frontend:
#    build: ./frontend
#    restart: always
#    depends_on:
#      - backend
#    ports:
#      - "4200:80"

volumes:
  db-data:
